/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.lyyj.activity.demo.gridview.gappsdraggridview;

import com.appfocusbase.R;

import android.widget.FrameLayout;
import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.widget.TextView;
import android.graphics.Rect;
import android.view.ViewGroup;
import android.util.Log;
public class DragLayer extends FrameLayout {
    
    public DragLayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
 /**   
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        super.onLayout(changed, l, t, r, b);
        int count = getChildCount();
        for(int i = 0x0; i < count; i = i + 0x1) {
            View child = getChildAt(i);
            FrameLayout.LayoutParams flp = (FrameLayout.LayoutParams)child.getLayoutParams();
            if(flp instanceof DragLayer.LayoutParams) {
                FrameLayout.LayoutParams lp = flp;
                if(lp!=null) { 
                    child.layout(l, t, (l + lp.width), (t + lp.height));
                }
            }
        }
    }
    */
    public boolean isHit(int x, int y) {
        Rect outRect = new Rect();
        findViewById(R.id.hittip).getHitRect(outRect);//view相对父视图坐�?
        int w = outRect.width();
        int h = outRect.height();
        final int[] location = new int[2];   
        findViewById(R.id.hittip).getLocationOnScreen(location); //view 屏幕坐标
        outRect.left =location[0];
        outRect.right =location[0]+w;
        outRect.top =location[1];
        outRect.bottom=location[1]+h;
        Log.e("DynamicGridView","kakadraglayer shortcut hitted x y  w h "+outRect.left+"*********"+outRect.top+"****"+outRect.right+"********"+outRect.bottom);
        return outRect.contains(x, y);
    }
    
    public void hitTip() {
        TextView tv = (TextView)findViewById(R.id.hittip);
        tv.setBackgroundColor(0xFF00FF00);
       // tv.setTextColor(0xFFFF0000);
        tv.setVisibility(View.VISIBLE);
    }
    
    public void unHitTip() {
        TextView tv = (TextView)findViewById(R.id.hittip);
        tv.setBackgroundColor(0x00000000);
       // tv.setTextColor(0xFFFFFFFF);
        tv.setVisibility(View.VISIBLE);
    }
    

}
